### ISSUE TITLE
Migration to TypeScript + Configuring Code Formatter, Lint and other standards

### ISSUE THREAD

**Issue by AndreisPurim** [AndreisPurim/MC426#10]
We need to decide on which code formatter, Lint and other standards we'll use in our project. Also fix any github repo configurations we might have missed, such as rules, automatic tests, etc...

**Comment by GustavoPurcena** [comment]
Changing issue scope to also cover migrating initial code base from JavaScript to TypeScript, while also configuring ESLint and Prettier. TypeScript will provide a larger set of tools and also add agility in our overall coding proccess along with ESLint and Prettier.
